title: 天翼云盘签到记录
description: 自动签到记录和统计
theme: minima
url: ""
baseurl: ""

# 站点信息
author:
  name: 天翼云盘签到机器人
  email: ""

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 排除文件
exclude:
  - README.md
  - main.py
  - requirements.txt
  - .env
  - .git/
  - .github/

# 页面设置
show_excerpts: false
header_pages:
  - index.md

# 导航设置
navigation:
  - title: 签到记录
    url: /
  - title: 项目主页
    url: https://github.com/{{ site.github.repository_nwo }}

# Markdown 设置
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# 主题设置
minima:
  skin: auto
  social_links:
    github: "{{ site.github.owner_name }}" 
